#!/bin/bash

#---------------------------------------------------------------
# c0ded by  : alinko a.k.a shutdown57
# contact   : alinkokomansuby@gmail.com
# Thanks to :
# indoXploit.or.id - stackoverflow.com - php.net - curl.haxx.se
#---------------------------------------------------------------
# copyright (c) 2k17 linuXcode.org
#-------------------------------------------------------------


#/*
#@ Auto Visitor Blog v3
#@ c0ded by shutdown572
#@ indonesianpeople.shutdown57@gmail.com
#*/

a_init_install(){
a_m="\033[1;31m"; # merah
a_k="\033[1;33m"; # kuning
a_h="\033[1;32m"; # hijau
a_n="\033[0m";    # netral
a_b="\033[1;34m"; # biru
printf"
   _________   ____    __________        
  /  _  \   \ /   /____\______   \ ____  
 /  /_\  \   Y   // __ \|    |  _// __ \ 
/    |    \     /\  ___/|    |   \  ___/ 
\____|__  /\___/  \___  >______  /\___  >
        \/            \/       \/     \/ 
+------------[[ AutoVisitor v3.0  ------------+
++-----------[[ by : shutdown57  -------------+
+--[[ indonesianpeople.shutdown57@gmail.com  -+
+---------------------------------------------+

"
echo -e $a_b"[!]$a_n Checking Dependencies ..."
sleep 1
which php > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	echo -e "[+]$a_h PHP...................OK!"$a_n
else
    echo -e "[-]$a_m PHP...................KO!"$a_n
    sleep 2
    clear
    echo "[+]$a_b Installing PHP ............."$a_n
    echo "[1] PHP5.x [2] PHP7.x [?] Default PHP5.x "
    echo -n "phpInstall >>" 
    read phpx
    if [[ $phpx == "1" ]]; then
     	apt-get install php5 php5-cli php5-curl curl
    elif [[ $phpx == "2" ]]; then
     	apt-get install php php-cli php-curl curl -y
     else
     	apt-get install php5 php5-cli php5-curl -y
     fi 
fi
sleep 1
which curl > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	echo -e "[+]$a_h CURL..................OK!"$a_n
else
	echo -e "[-]$a_m CURL..................KO!"$a_n
    sleep 2
	clear
    echo "[+]$a_b Installing CuRL............"$a_n
    apt-get install curl -y
fi
sleep 2
echo "Click [enter] to accept license :"
read enter
clear
more LICENSE.txt
clear
echo "AVB v3.0 will installed to '/opt/avb/' "
sleep 1
echo -e $a_h"[+]$a_n Creating Directory..."
mkdir -p /opt/avb
sleep 1
echo -e $a_h"[+]$a_n Installing AVeBe v3.0 ...."
chmod 755 -R desktop/
sleep 1
cp -r * /opt/avb/ > /dev/null 2>&1
cp desktop/avb.desktop /opt/avb/ > /dev/null 2>&1
echo -e $a_h"[+]$a_n Creating desktop icon"
cp desktop/avb.png /opt/avb/ > /dev/null 2>&1
cp desktop/avb.desktop /usr/share/applications/ > /dev/null 2>&1
cp autorun.sh /usr/bin/avebe > /dev/null 2>&1
sleep 1
echo -e $a_b"INSTALLATION FINISHED!"
}
	if [[ `whoami` == "root" ]]; then
		a_init_install
	else
		echo "[!] You Must be Root to install this tool. "
	fi
