#!/bin/bash


a_init_install(){
a_m="\033[1;31m"; # merah
a_k="\033[1;33m"; # kuning
a_h="\033[1;32m"; # hijau
a_n="\033[0m";    # netral
a_b="\033[1;34m"; # biru
printf " ___.-. ___        _  ____   ____  ______            __     ___  ___.-. 
|  ___||  _|      / \|_  _| |_  _||_   _ \          /  |   |_  ||  ___| 
'-'    | |       / _ \ \ \   / /    | |_) |   _   __'| |     | |'-'     
       | |      / ___ \ \ \ / /     |  __'.  [ \ [  ]| |     | |        
       | |_   _/ /   \ \_\ ' /     _| |__) |  \ \/ /_| |_   _| |        
       |___| |____| |____|\_/     |_______/    \__/|_____| |___|        

+----------------------------------------------------------------------------+
|               $a_m  Script Installer AutoVisitorBlogv12017 $a_n                    | 
+----------------------------------------------------------------------------+
"
echo -e $a_b"[!]$a_n Checking Dependencies ..."
sleep 1
which php > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	echo -e "[+]$a_h PHP...................OK!"$a_n
else
    echo -e "[-]$a_m PHP...................KO!"$a_n
    exit 1
fi
sleep 1
which curl > /dev/null 2>&1
if [[ "$?" -eq "0" ]]; then
	echo -e "[+]$a_h CURL..................OK!"$a_n
else
	echo -e "[-]$a_m CURL..................KO!"$a_n
	exit 1
fi
sleep 2
echo "Click [enter] to accept license :"
read enter
more LICENSE.txt

echo "AVB v1 will installed to '/opt/avb/' "
sleep 1
echo -e $a_h"[+]$a_n Creating Directory..."
mkdir /opt/avb
sleep 1
echo -e $a_h"[+]$a_n Installing AVB v1...."
chmod 777 -R *
chmod 777 -R desktop/
sleep 1
cp * /opt/avb/
cp desktop/avb.desktop /opt/avb/
echo -e $a_h"[+]$a_n Creating desktop icon"
cp desktop/avb.png /opt/avb/
cp desktop/avb.desktop /usr/share/applications/
cp autorun.sh /usr/bin/avb
sleep 1
echo -e $a_b"INSTALLATION FINISHED!"
}
	if [[ `whoami` == "root" ]]; then
		a_init_install
	else
		echo "[!] You Must be Root to install this tool. "
	fi